# Logstash Configuration
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# Pipeline settings
pipeline.workers: 2
pipeline.output.workers: 1
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Monitoring
monitoring.enabled: true

# Queue settings
queue.type: memory
